In [1]:
def task1():
    n = int(input("Enter n: "))
    arr = [[0 for j in range(n)] for i in range(n)]
    
    for i in range(n):
        arr[i][i] = i + 1

    for row in arr:
        print(row)
        
        
%time task1()

Enter n: 5
[1, 0, 0, 0, 0]
[0, 2, 0, 0, 0]
[0, 0, 3, 0, 0]
[0, 0, 0, 4, 0]
[0, 0, 0, 0, 5]
CPU times: user 61.4 ms, sys: 21 ms, total: 82.4 ms
Wall time: 3.49 s


In [2]:
def task5():
    n = int(input("Enter n: "))
    
    arr = [[0 for j in range(n)] for i in range(n)]
    
    for i in range(n):
        if i % 2 == 0:
            for j in range(n):
                arr[i][j] = 1
                
    for row in arr:
        print(row)
        
%time task5()

Enter n: 5
[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
[0, 0, 0, 0, 0]
[1, 1, 1, 1, 1]
CPU times: user 40.6 ms, sys: 14.9 ms, total: 55.5 ms
Wall time: 2.07 s


In [5]:
def task7(array):
    for i in range(len(array)):
        if array[i] == 0:
            array[i] = -1
    print(array)

%time task7([0,9,0,0,10,0,1])

[-1, 9, -1, -1, 10, -1, 1]
CPU times: user 361 µs, sys: 161 µs, total: 522 µs
Wall time: 397 µs


In [7]:
def task8(array):
    count_zeros = 0
    count_non_zeros = 0

    for element in array:
        if element == 0:
            count_zeros += 1
        else:
            count_non_zeros += 1

    print(count_zeros)
    print(count_non_zeros)

%time task8([-1,3,0,0,0,0,0])

5
2
CPU times: user 201 µs, sys: 446 µs, total: 647 µs
Wall time: 2.13 ms


In [4]:
def task12():
    n = int(input("Enter n: "))
    
    arr = [[1 for j in range(n)] for i in range(n)]
    
    arr[0] = [0 for i in range(n)]
    arr[n-1] = [0 for i in range(n)]
    
    for i in range(1, n-1):
        for j in range(n):
            if j == 0 or j == n - 1:
                arr[i][j] = 0
                
    for row in arr:
        print(row)
        
%time task12()

Enter n: 6
[0, 0, 0, 0, 0, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 1, 1, 1, 1, 0]
[0, 0, 0, 0, 0, 0]
CPU times: user 35.2 ms, sys: 14 ms, total: 49.2 ms
Wall time: 1.64 s


In [7]:
def task16():
    n = int(input("Enter n: "))
    
    arr = [i for i in range(n+1)]
    
    for i in range(n+1):
        if n/4 < i and i < 3*n/4:
            arr[i] = 0
            
    print(arr)
        
%time task16()

Enter n: 5
[0, 1, 0, 0, 4, 5]
CPU times: user 24.4 ms, sys: 13.2 ms, total: 37.6 ms
Wall time: 2.16 s


In [8]:
def task17():
    n = int(input("Enter n: "))
    
    arr = [i for i in range(n+1)]
    
    for i in range(n+1):
        if i < n/2 or i > 3*n/4:
            arr[i] *= -1
            
    print(arr)
        
%time task17()

Enter n: 6
[0, -1, -2, 3, 4, -5, -6]
CPU times: user 30.1 ms, sys: 11 ms, total: 41.1 ms
Wall time: 1.69 s


In [9]:
import random

def task21():
    n = int(input("Enter n: "))
    m = int(input("Enter m: "))
    
    arr = [[random.randint(0, m) for j in range(n)] for i in range(n)]
    
    for row in arr:
        print(row)
        
    arr_max = max(max(arr[i]) for i in range(n))
    for i in range(n):
        for j in range(n):
            if arr[i][j] == arr_max:
                arr[i][j] *= -1
                
    for row in arr:
        print(row)
        
%time task21()

Enter n: 5
Enter m: 5
[0, 0, 2, 2, 3]
[1, 2, 0, 5, 2]
[4, 5, 4, 3, 5]
[3, 2, 3, 5, 1]
[0, 1, 5, 0, 5]
[0, 0, 2, 2, 3]
[1, 2, 0, -5, 2]
[4, -5, 4, 3, -5]
[3, 2, 3, -5, 1]
[0, 1, -5, 0, -5]
CPU times: user 105 ms, sys: 37.6 ms, total: 142 ms
Wall time: 5.44 s


In [16]:
import numpy as np
import sympy


A = np.array([[5, 1, 0, -1],
    [3,  -3,  1, 4],
    [3, 0, -2, 1],
    [1, -4, 0, 1]])

B = np.array([-9, -7, -16, 0])


def kernel_method(A, b):
    # Об'єднання матриці A та вектору b для отримання розширеної матриці
    augmented_matrix = np.column_stack((A, b))

    # Зведення до ступеневої форми
    rref, pivot_cols = sympy.Matrix(augmented_matrix).rref()

    # Знаходження розв'язків однорідної системи
    kernel_matrix = rref[:, :-1]
    kernel_basis = sympy.Matrix(kernel_matrix).nullspace()

    # Знаходження частини загального розв'язку
    particular_solution = np.array([])
    for col_idx in range(kernel_matrix.shape[1]):
        if col_idx not in pivot_cols:
            free_col = np.array(kernel_basis[0]).reshape(-1, 1) 
            particular_solution = np.hstack((particular_solution, free_col))

    # Знаходження партікулярного розв'язку неоднорідної системи
    particular_solution = np.linalg.lstsq(A, b, rcond=None)[0]

    # Знаходження загального розв'язку
    general_solution = particular_solution + kernel_matrix @ particular_solution

    return general_solution



print(kernel_method(A, B))


[-4.00000000000000 -2.00000000000000 8.00000000000000 -4.00000000000000]


In [23]:
import numpy as np

def task_3():
    A = np.array([[1, -2, 3], [2, 3, 5], [1, 4, -1]])
    B = np.array([[4, 11, 3], [1, 6, 1], [2, 2, 16]])

    # (A + B)A - B(2A+3B)

    C = np.subtract(np.multiply(np.add(A, B), A), np.multiply(B, (np.add(np.multiply(A, 2), np.multiply(B,3)))))

    print("A:")
    print(A)
    print("\nB:")
    print(B)
    print("\n(A - B)A + 3B:")
    print(C)

%time task_3()

A:
[[ 1 -2  3]
 [ 2  3  5]
 [ 1  4 -1]]

B:
[[ 4 11  3]
 [ 1  6  1]
 [ 2  2 16]]

(A - B)A + 3B:
[[ -51 -337  -27]
 [  -1 -117   17]
 [ -13   -4 -751]]
CPU times: user 1.45 ms, sys: 1.18 ms, total: 2.63 ms
Wall time: 4.33 ms
